DefaultContentLanguage = "en"
baseurl = "https://www.spokanemtb.org"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
paginate = 3
pluralizeListTitles = false
theme = "hugo-future-imperfect-slim"
title = "Spokane Youth Mountain Biking"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
identifier = "home"
name = "Home"
pre = "<i class='fa fa-home'></i>"
weight = 1
[[menu.main]]
identifier = "blog"
name = "Blog"
pre = "<i class='far fa-newspaper'></i>"
url = "blog"
weight = 3
[[menu.main]]
identifier = "categories"
name = "Categories"
pre = "<i class='fas fa-sitemap'></i>"
url = "categories"
weight = 4
[[menu.main]]
identifier = "contact"
name = "Contact"
pre = "<i class='far fa-envelope'></i>"
url = "contact"
weight = 5
[module.hugoVersion]
extended = true
min = "0.62.0"
[outputs]
home = ["html", "json", "rss"]
[params]
cssFiles = ["default"]
enableCDN = false
hideEmptyStats = false
highlightjs = true
highlightjsLang = []
highlightjsTheme = ""
imageStretch = ""
jsFiles = ["default"]
readingTime = true
removeBlur = false
socialShare = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]
toc = true
tocWords = 400
viewMorePostsLink = "blog"
[params.footer]
rssFooter = true
socialFooter = true
[params.header]
dynamicTitles = true
languageMenu = true
navbarTitle = "Spokane Youth MTB"
searchMenu = true
shareMenu = true
[params.intro]
alwaysOnHomepage = false
header = "Spokane Youth MTB"
hideWhenSingleColumn = false
paragraph = "Home for Spokane Youth Mountain Biking.  We like bikes!"
rssIntro = true
socialIntro = true
[params.intro.pic]
alt = "Spokane Youth MTB"
shape = "rectangle"
src = "img/logo.png"
width = "250"
[params.meta]
author = "Moose, Bombers and more!"
description = "Spokane Youth mountain biking information site.  Home page for the Spokane Valley Moose, Spokane Composite Bombers."
favicon = false
faviconVersion = "1"
iOSColor = "#ffffff"
msColor = "#ffffff"
svg = true
[params.sidebar]
about = "Spokane Youth Mountain Biking"
categories = false
categoriesByCount = false
postAmount = 5
[params.staticman]
api = ""
branch = ""
enabled = false
gitProvider = ""
repo = ""
username = ""
[params.staticman.recaptcha]
encryptedKey = ""
siteKey = ""
[params.utterances]
enabled = false
issueNumber = ""
issueTerm = "pathname"
label = ""
repo = ""
theme = "github-light"
[social]
behance = ""
bitbucket = ""
codepen = ""
deviantart = ""
dribbble = ""
email = "spokanevalleymoose@gmail.com"
facebook = "example"
flickr = ""
foursquare = ""
github = "scottanious/mtbsite"
gitlab = ""
googleplus = ""
googlescholar = ""
instagram = "spokanevalleycompositemtb"
jsfiddle = ""
keybase = ""
linkedin = ""
linkedin_company = ""
mastodon = ""
medium = ""
orcid = ""
pinterest = ""
qq = ""
quora = ""
reddit = ""
researchgate = ""
skype = ""
slideshare = ""
snapchat = ""
stackoverflow = ""
strava = ""
telegram = ""
tumblr = ""
twitter = ""
vimeo = ""
vine = ""
wechat = ""
whatsapp = ""
wordpress = ""
xing = ""
youtube = ""
